---
name: Rubocop

on: [pull_request, push, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run rubocop
        run: |
          PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
          echo $PATH
          gem install --user-install rubocop
          rubocop --auto-correct-all --disable-uncorrectable
      - name: Check for changes
        run: |
          modified=$(git status | grep modified | wc -l)
          if [ $modified -gt 0 ];
          then
              git config --local user.email "$(git log --format='%ae' HEAD^!)"
              git config --local user.name "$(git log --format='%an' HEAD^!)"
              git add --all;
              git commit -m "Committing files modified by rubocop";
              git push;
          fi
